### ISSUE TITLE
NullPointerException after building into .jar

### ISSUE THREAD

**Issue by pabsilva** [Serbroda/thymeleaf-component-dialect#1]
Hi there,

First of all, congratulations on this great extension, it's definitely something that was missing in thymeleaf!

Unfortunately, I noticed a problem that occurs only after I build my spring application into a .jar. When I try to access a page that uses features of this dialect, I get the following exception:

```
java.lang.NullPointerException: null
        at de.morphbit.thymeleaf.helper.ResourcePathFinder.getResourceFiles(ResourcePathFinder.java:56) ~[thymeleaf-component-dialect-0.0.3-alpha.jar!/:na]
        at de.morphbit.thymeleaf.helper.ResourcePathFinder.findResourceFiles(ResourcePathFinder.java:49) ~[thymeleaf-component-dialect-0.0.3-alpha.jar!/:na]
        at de.morphbit.thymeleaf.parser.StandardThymeleafComponentParser.parse(StandardThymeleafComponentParser.java:63) ~[thymeleaf-component-dialect-0.0.3-alpha.jar!/:na]
        at de.morphbit.thymeleaf.dialect.ComponentDialect.parseComponents(ComponentDialect.java:97) ~[thymeleaf-component-dialect-0.0.3-alpha.jar!/:na]
        at de.morphbit.thymeleaf.dialect.ComponentDialect.getProcessors(ComponentDialect.java:81) ~[thymeleaf-component-dialect-0.0.3-alpha.jar!/:na]
        at org.thymeleaf.DialectSetConfiguration.build(DialectSetConfiguration.java:152) ~[thymeleaf-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        at org.thymeleaf.EngineConfiguration.<init>(EngineConfiguration.java:123) ~[thymeleaf-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        at org.thymeleaf.TemplateEngine.initialize(TemplateEngine.java:336) ~[thymeleaf-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        at org.thymeleaf.TemplateEngine.getConfiguration(TemplateEngine.java:406) ~[thymeleaf-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:254) ~[thymeleaf-spring4-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:191) ~[thymeleaf-spring4-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
```

Looking at the code, the problem seems to be in this location:

```
private List<String> getResourceFiles(String dir, List<String> files,
	        boolean recursively) {
		URL url = loader.getResource(dir);
		String path = url.getPath();
		for (File file : new File(path).listFiles()) {
			if (recursively && file.isDirectory()) {
				return getResourceFiles(concatPath(dir, file.getName()), files,
				    recursively);
			} else {
				files.add(concatPath(dir, file.getName()));
			}
		}
		return files;
	}
```
Given that the problem only occurs in the bundled app into an app, I believe the issue may lie in the fact that you can't run the "new File(path).listFiles()" because you can't grab the resources while inside the .jar.

Any thoughts on how this could be fixed?

(Sorry, I've erroneously opened this issue in the demo project repo)

**Comment by Serbroda** [comment]
Solved by #2
